### ISSUE TITLE
Comments with emoji in them are failing in production (mysql issue)

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#333]
See https://app.bugsnag.com/alonetone/alonetone/errors/5c00ba65d732580019e911f1?event_id=5c00ba6500313864852d0000&i=sk&m=nw

**Comment by innatewonderer** [comment]
Notes:
When I try to test this character: 🎶🎶
I get the following error:
```
Mysql2::Error: Illegal mix of collations (utf8mb4_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE)
```
I was able to `ALTER TABLE comments CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;` which allowed me to save ☺

**Comment by sudara** [comment]
Interesting!

Did you run migrations after this was merged yesterday? https://github.com/sudara/alonetone/pull/388

**Comment by sudara** [comment]
Looks like I get that error locally too:

`ActiveRecord::StatementInvalid (Mysql2::Error: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `comments`.* FROM `comments` WHERE `comments`.`remote_ip` = '::1' AND `comments`.`body` = '🎶' ORDER BY `comments`.`id` ASC LIMIT 1):
```

/cc @Manfred

**Comment by Manfred** [comment]
You have to make sure your connection encoding matches the database encoding. I have the following in `config/database.yml`:

```yaml
development:
  adapter: mysql2
  encoding: utf8mb4
  database: alonetone_development
  pool: 5
  host: localhost
  variables:
    sql_mode: TRADITIONAL
test:
  adapter: mysql2
  encoding: utf8mb4
  database: alonetone_test
  pool: 5
  host: localhost
  variables:
    sql_mode: TRADITIONAL
```

In production we probably need to switch to `encoding: utf8mb4` too.
